module.exports.topTracks = {
  "href": "https://api.spotify.com/v1/albums/0BwWUstDMUbgq2NYONRqlu/tracks?offset=0&limit=20",
  "items": [
      {
          "artists": [
              {
                  "external_urls": {
                      "spotify": "https://open.spotify.com/artist/08GQAI4eElDnROBrJRGE0X"
                  },
                  "href": "https://api.spotify.com/v1/artists/08GQAI4eElDnROBrJRGE0X",
                  "id": "08GQAI4eElDnROBrJRGE0X",
                  "name": "Fleetwood Mac",
                  "type": "artist",
                  "uri": "spotify:artist:08GQAI4eElDnROBrJRGE0X"
              }
          ],
          "available_markets": [
              "AD",
              "AE",
              "AG",
              "AL",
              "AM",
              "AO",
              "AR",
              "AT",
              "AU",
              "AZ",
              "BA",
              "BB",
              "BD",
              "BE",
              "BF",
              "BG",
              "BH",
              "BI",
              "BJ",
              "BN",
              "BO",
              "BR",
              "BS",
              "BW",
              "BY",
              "BZ",
              "CA",
              "CH",
              "CI",
              "CL",
              "CM",
              "CO",
              "CR",
              "CV",
              "CW",
              "CY",
              "CZ",
              "DE",
              "DJ",
              "DK",
              "DM",
              "DO",
              "DZ",
              "EC",
              "EE",
              "EG",
              "ES",
              "FI",
              "FJ",
              "FM",
              "FR",
              "GA",
              "GB",
              "GD",
              "GE",
              "GH",
              "GM",
              "GN",
              "GQ",
              "GR",
              "GT",
              "GW",
              "HK",
              "HN",
              "HR",
              "HT",
              "HU",
              "ID",
              "IE",
              "IL",
              "IN",
              "IS",
              "IT",
              "JM",
              "JO",
              "JP",
              "KE",
              "KG",
              "KH",
              "KM",
              "KN",
              "KR",
              "KW",
              "KZ",
              "LA",
              "LB",
              "LC",
              "LK",
              "LR",
              "LS",
              "LT",
              "LU",
              "LV",
              "MA",
              "MC",
              "MD",
              "ME",
              "MG",
              "MK",
              "ML",
              "MN",
              "MO",
              "MR",
              "MT",
              "MU",
              "MW",
              "MX",
              "MY",
              "MZ",
              "NA",
              "NE",
              "NG",
              "NI",
              "NL",
              "NO",
              "NP",
              "NZ",
              "OM",
              "PA",
              "PE",
              "PG",
              "PH",
              "PK",
              "PL",
              "PT",
              "PY",
              "QA",
              "RO",
              "RS",
              "RU",
              "RW",
              "SA",
              "SC",
              "SE",
              "SG",
              "SI",
              "SK",
              "SL",
              "SM",
              "SN",
              "ST",
              "SV",
              "SZ",
              "TD",
              "TG",
              "TH",
              "TL",
              "TN",
              "TR",
              "TT",
              "TW",
              "TZ",
              "UA",
              "UG",
              "US",
              "UY",
              "UZ",
              "VC",
              "VN",
              "XK",
              "ZA",
              "ZM",
              "ZW"
          ],
          "disc_number": 1,
          "duration_ms": 176306,
          "explicit": false,
          "external_urls": {
              "spotify": "https://open.spotify.com/track/4SZhxF0sIS8nDvwhT0Tt2V"
          },
          "href": "https://api.spotify.com/v1/tracks/4SZhxF0sIS8nDvwhT0Tt2V",
          "id": "4SZhxF0sIS8nDvwhT0Tt2V",
          "is_local": false,
          "name": "Second Hand News - 2004 Remaster",
          "preview_url": "https://p.scdn.co/mp3-preview/c369d638a1874dbf90101a44325ca8503eca8ea1?cid=88e83947e4fb497e9c85307e40abab6c",
          "track_number": 1,
          "type": "track",
          "uri": "spotify:track:4SZhxF0sIS8nDvwhT0Tt2V"
      },
      {
          "artists": [
              {
                  "external_urls": {
                      "spotify": "https://open.spotify.com/artist/08GQAI4eElDnROBrJRGE0X"
                  },
                  "href": "https://api.spotify.com/v1/artists/08GQAI4eElDnROBrJRGE0X",
                  "id": "08GQAI4eElDnROBrJRGE0X",
                  "name": "Fleetwood Mac",
                  "type": "artist",
                  "uri": "spotify:artist:08GQAI4eElDnROBrJRGE0X"
              }
          ],
          "available_markets": [
              "AD",
              "AE",
              "AG",
              "AL",
              "AM",
              "AO",
              "AR",
              "AT",
              "AU",
              "AZ",
              "BA",
              "BB",
              "BD",
              "BE",
              "BF",
              "BG",
              "BH",
              "BI",
              "BJ",
              "BN",
              "BO",
              "BR",
              "BS",
              "BW",
              "BY",
              "BZ",
              "CA",
              "CH",
              "CI",
              "CL",
              "CM",
              "CO",
              "CR",
              "CV",
              "CW",
              "CY",
              "CZ",
              "DE",
              "DJ",
              "DK",
              "DM",
              "DO",
              "DZ",
              "EC",
              "EE",
              "EG",
              "ES",
              "FI",
              "FJ",
              "FM",
              "FR",
              "GA",
              "GB",
              "GD",
              "GE",
              "GH",
              "GM",
              "GN",
              "GQ",
              "GR",
              "GT",
              "GW",
              "HK",
              "HN",
              "HR",
              "HT",
              "HU",
              "ID",
              "IE",
              "IL",
              "IN",
              "IS",
              "IT",
              "JM",
              "JO",
              "JP",
              "KE",
              "KG",
              "KH",
              "KM",
              "KN",
              "KR",
              "KW",
              "KZ",
              "LA",
              "LB",
              "LC",
              "LK",
              "LR",
              "LS",
              "LT",
              "LU",
              "LV",
              "MA",
              "MC",
              "MD",
              "ME",
              "MG",
              "MK",
              "ML",
              "MN",
              "MO",
              "MR",
              "MT",
              "MU",
              "MW",
              "MX",
              "MY",
              "MZ",
              "NA",
              "NE",
              "NG",
              "NI",
              "NL",
              "NO",
              "NP",
              "NZ",
              "OM",
              "PA",
              "PE",
              "PG",
              "PH",
              "PK",
              "PL",
              "PT",
              "PY",
              "QA",
              "RO",
              "RS",
              "RU",
              "RW",
              "SA",
              "SC",
              "SE",
              "SG",
              "SI",
              "SK",
              "SL",
              "SM",
              "SN",
              "ST",
              "SV",
              "SZ",
              "TD",
              "TG",
              "TH",
              "TL",
              "TN",
              "TR",
              "TT",
              "TW",
              "TZ",
              "UA",
              "UG",
              "US",
              "UY",
              "UZ",
              "VC",
              "VN",
              "XK",
              "ZA",
              "ZM",
              "ZW"
          ],
          "disc_number": 1,
          "duration_ms": 257800,
          "explicit": false,
          "external_urls": {
              "spotify": "https://open.spotify.com/track/0ofHAoxe9vBkTCp2UQIavz"
          },
          "href": "https://api.spotify.com/v1/tracks/0ofHAoxe9vBkTCp2UQIavz",
          "id": "0ofHAoxe9vBkTCp2UQIavz",
          "is_local": false,
          "name": "Dreams - 2004 Remaster",
          "preview_url": "https://p.scdn.co/mp3-preview/40d1f6d82f16b05b62aae47e8e130de04b407fc8?cid=88e83947e4fb497e9c85307e40abab6c",
          "track_number": 2,
          "type": "track",
          "uri": "spotify:track:0ofHAoxe9vBkTCp2UQIavz"
      },
      {
          "artists": [
              {
                  "external_urls": {
                      "spotify": "https://open.spotify.com/artist/08GQAI4eElDnROBrJRGE0X"
                  },
                  "href": "https://api.spotify.com/v1/artists/08GQAI4eElDnROBrJRGE0X",
                  "id": "08GQAI4eElDnROBrJRGE0X",
                  "name": "Fleetwood Mac",
                  "type": "artist",
                  "uri": "spotify:artist:08GQAI4eElDnROBrJRGE0X"
              }
          ],
          "available_markets": [
              "AD",
              "AE",
              "AG",
              "AL",
              "AM",
              "AO",
              "AR",
              "AT",
              "AU",
              "AZ",
              "BA",
              "BB",
              "BD",
              "BE",
              "BF",
              "BG",
              "BH",
              "BI",
              "BJ",
              "BN",
              "BO",
              "BR",
              "BS",
              "BW",
              "BY",
              "BZ",
              "CA",
              "CH",
              "CI",
              "CL",
              "CM",
              "CO",
              "CR",
              "CV",
              "CW",
              "CY",
              "CZ",
              "DE",
              "DJ",
              "DK",
              "DM",
              "DO",
              "DZ",
              "EC",
              "EE",
              "EG",
              "ES",
              "FI",
              "FJ",
              "FM",
              "FR",
              "GA",
              "GB",
              "GD",
              "GE",
              "GH",
              "GM",
              "GN",
              "GQ",
              "GR",
              "GT",
              "GW",
              "HK",
              "HN",
              "HR",
              "HT",
              "HU",
              "ID",
              "IE",
              "IL",
              "IN",
              "IS",
              "IT",
              "JM",
              "JO",
              "JP",
              "KE",
              "KG",
              "KH",
              "KM",
              "KN",
              "KR",
              "KW",
              "KZ",
              "LA",
              "LB",
              "LC",
              "LK",
              "LR",
              "LS",
              "LT",
              "LU",
              "LV",
              "MA",
              "MC",
              "MD",
              "ME",
              "MG",
              "MK",
              "ML",
              "MN",
              "MO",
              "MR",
              "MT",
              "MU",
              "MW",
              "MX",
              "MY",
              "MZ",
              "NA",
              "NE",
              "NG",
              "NI",
              "NL",
              "NO",
              "NP",
              "NZ",
              "OM",
              "PA",
              "PE",
              "PG",
              "PH",
              "PK",
              "PL",
              "PT",
              "PY",
              "QA",
              "RO",
              "RS",
              "RU",
              "RW",
              "SA",
              "SC",
              "SE",
              "SG",
              "SI",
              "SK",
              "SL",
              "SM",
              "SN",
              "ST",
              "SV",
              "SZ",
              "TD",
              "TG",
              "TH",
              "TL",
              "TN",
              "TR",
              "TT",
              "TW",
              "TZ",
              "UA",
              "UG",
              "US",
              "UY",
              "UZ",
              "VC",
              "VN",
              "XK",
              "ZA",
              "ZM",
              "ZW"
          ],
          "disc_number": 1,
          "duration_ms": 134400,
          "explicit": false,
          "external_urls": {
              "spotify": "https://open.spotify.com/track/19Shlms2uTnOjIUg50TXzd"
          },
          "href": "https://api.spotify.com/v1/tracks/19Shlms2uTnOjIUg50TXzd",
          "id": "19Shlms2uTnOjIUg50TXzd",
          "is_local": false,
          "name": "Never Going Back Again - 2004 Remaster",
          "preview_url": "https://p.scdn.co/mp3-preview/e2a3257f4736ce1e87dc8aca8a820a17d5e326eb?cid=88e83947e4fb497e9c85307e40abab6c",
          "track_number": 3,
          "type": "track",
          "uri": "spotify:track:19Shlms2uTnOjIUg50TXzd"
      },
      {
          "artists": [
              {
                  "external_urls": {
                      "spotify": "https://open.spotify.com/artist/08GQAI4eElDnROBrJRGE0X"
                  },
                  "href": "https://api.spotify.com/v1/artists/08GQAI4eElDnROBrJRGE0X",
                  "id": "08GQAI4eElDnROBrJRGE0X",
                  "name": "Fleetwood Mac",
                  "type": "artist",
                  "uri": "spotify:artist:08GQAI4eElDnROBrJRGE0X"
              }
          ],
          "available_markets": [
              "AD",
              "AE",
              "AG",
              "AL",
              "AM",
              "AO",
              "AR",
              "AT",
              "AU",
              "AZ",
              "BA",
              "BB",
              "BD",
              "BE",
              "BF",
              "BG",
              "BH",
              "BI",
              "BJ",
              "BN",
              "BO",
              "BR",
              "BS",
              "BW",
              "BY",
              "BZ",
              "CA",
              "CH",
              "CI",
              "CL",
              "CM",
              "CO",
              "CR",
              "CV",
              "CW",
              "CY",
              "CZ",
              "DE",
              "DJ",
              "DK",
              "DM",
              "DO",
              "DZ",
              "EC",
              "EE",
              "EG",
              "ES",
              "FI",
              "FJ",
              "FM",
              "FR",
              "GA",
              "GB",
              "GD",
              "GE",
              "GH",
              "GM",
              "GN",
              "GQ",
              "GR",
              "GT",
              "GW",
              "HK",
              "HN",
              "HR",
              "HT",
              "HU",
              "ID",
              "IE",
              "IL",
              "IN",
              "IS",
              "IT",
              "JM",
              "JO",
              "JP",
              "KE",
              "KG",
              "KH",
              "KM",
              "KN",
              "KR",
              "KW",
              "KZ",
              "LA",
              "LB",
              "LC",
              "LK",
              "LR",
              "LS",
              "LT",
              "LU",
              "LV",
              "MA",
              "MC",
              "MD",
              "ME",
              "MG",
              "MK",
              "ML",
              "MN",
              "MO",
              "MR",
              "MT",
              "MU",
              "MW",
              "MX",
              "MY",
              "MZ",
              "NA",
              "NE",
              "NG",
              "NI",
              "NL",
              "NO",
              "NP",
              "NZ",
              "OM",
              "PA",
              "PE",
              "PG",
              "PH",
              "PK",
              "PL",
              "PT",
              "PY",
              "QA",
              "RO",
              "RS",
              "RU",
              "RW",
              "SA",
              "SC",
              "SE",
              "SG",
              "SI",
              "SK",
              "SL",
              "SM",
              "SN",
              "ST",
              "SV",
              "SZ",
              "TD",
              "TG",
              "TH",
              "TL",
              "TN",
              "TR",
              "TT",
              "TW",
              "TZ",
              "UA",
              "UG",
              "US",
              "UY",
              "UZ",
              "VC",
              "VN",
              "XK",
              "ZA",
              "ZM",
              "ZW"
          ],
          "disc_number": 1,
          "duration_ms": 193346,
          "explicit": false,
          "external_urls": {
              "spotify": "https://open.spotify.com/track/3CPeWqqaHR0hmyfsWhMJQs"
          },
          "href": "https://api.spotify.com/v1/tracks/3CPeWqqaHR0hmyfsWhMJQs",
          "id": "3CPeWqqaHR0hmyfsWhMJQs",
          "is_local": false,
          "name": "Don't Stop - 2004 Remaster",
          "preview_url": "https://p.scdn.co/mp3-preview/45a7eb3cd757473e80584b5cda0969c67841f1e6?cid=88e83947e4fb497e9c85307e40abab6c",
          "track_number": 4,
          "type": "track",
          "uri": "spotify:track:3CPeWqqaHR0hmyfsWhMJQs"
      },
      {
          "artists": [
              {
                  "external_urls": {
                      "spotify": "https://open.spotify.com/artist/08GQAI4eElDnROBrJRGE0X"
                  },
                  "href": "https://api.spotify.com/v1/artists/08GQAI4eElDnROBrJRGE0X",
                  "id": "08GQAI4eElDnROBrJRGE0X",
                  "name": "Fleetwood Mac",
                  "type": "artist",
                  "uri": "spotify:artist:08GQAI4eElDnROBrJRGE0X"
              }
          ],
          "available_markets": [
              "AD",
              "AE",
              "AG",
              "AL",
              "AM",
              "AO",
              "AR",
              "AT",
              "AU",
              "AZ",
              "BA",
              "BB",
              "BD",
              "BE",
              "BF",
              "BG",
              "BH",
              "BI",
              "BJ",
              "BN",
              "BO",
              "BR",
              "BS",
              "BW",
              "BY",
              "BZ",
              "CA",
              "CH",
              "CI",
              "CL",
              "CM",
              "CO",
              "CR",
              "CV",
              "CW",
              "CY",
              "CZ",
              "DE",
              "DJ",
              "DK",
              "DM",
              "DO",
              "DZ",
              "EC",
              "EE",
              "EG",
              "ES",
              "FI",
              "FJ",
              "FM",
              "FR",
              "GA",
              "GB",
              "GD",
              "GE",
              "GH",
              "GM",
              "GN",
              "GQ",
              "GR",
              "GT",
              "GW",
              "HK",
              "HN",
              "HR",
              "HT",
              "HU",
              "ID",
              "IE",
              "IL",
              "IN",
              "IS",
              "IT",
              "JM",
              "JO",
              "JP",
              "KE",
              "KG",
              "KH",
              "KM",
              "KN",
              "KR",
              "KW",
              "KZ",
              "LA",
              "LB",
              "LC",
              "LK",
              "LR",
              "LS",
              "LT",
              "LU",
              "LV",
              "MA",
              "MC",
              "MD",
              "ME",
              "MG",
              "MK",
              "ML",
              "MN",
              "MO",
              "MR",
              "MT",
              "MU",
              "MW",
              "MX",
              "MY",
              "MZ",
              "NA",
              "NE",
              "NG",
              "NI",
              "NL",
              "NO",
              "NP",
              "NZ",
              "OM",
              "PA",
              "PE",
              "PG",
              "PH",
              "PK",
              "PL",
              "PT",
              "PY",
              "QA",
              "RO",
              "RS",
              "RU",
              "RW",
              "SA",
              "SC",
              "SE",
              "SG",
              "SI",
              "SK",
              "SL",
              "SM",
              "SN",
              "ST",
              "SV",
              "SZ",
              "TD",
              "TG",
              "TH",
              "TL",
              "TN",
              "TR",
              "TT",
              "TW",
              "TZ",
              "UA",
              "UG",
              "US",
              "UY",
              "UZ",
              "VC",
              "VN",
              "XK",
              "ZA",
              "ZM",
              "ZW"
          ],
          "disc_number": 1,
          "duration_ms": 223613,
          "explicit": false,
          "external_urls": {
              "spotify": "https://open.spotify.com/track/4xh7W7tlNMIczFhupCPniY"
          },
          "href": "https://api.spotify.com/v1/tracks/4xh7W7tlNMIczFhupCPniY",
          "id": "4xh7W7tlNMIczFhupCPniY",
          "is_local": false,
          "name": "Go Your Own Way - 2004 Remaster",
          "preview_url": "https://p.scdn.co/mp3-preview/302c9a7eb9231f5d3deccd69830473d20475bc92?cid=88e83947e4fb497e9c85307e40abab6c",
          "track_number": 5,
          "type": "track",
          "uri": "spotify:track:4xh7W7tlNMIczFhupCPniY"
      },
      {
          "artists": [
              {
                  "external_urls": {
                      "spotify": "https://open.spotify.com/artist/08GQAI4eElDnROBrJRGE0X"
                  },
                  "href": "https://api.spotify.com/v1/artists/08GQAI4eElDnROBrJRGE0X",
                  "id": "08GQAI4eElDnROBrJRGE0X",
                  "name": "Fleetwood Mac",
                  "type": "artist",
                  "uri": "spotify:artist:08GQAI4eElDnROBrJRGE0X"
              }
          ],
          "available_markets": [
              "AD",
              "AE",
              "AG",
              "AL",
              "AM",
              "AO",
              "AR",
              "AT",
              "AU",
              "AZ",
              "BA",
              "BB",
              "BD",
              "BE",
              "BF",
              "BG",
              "BH",
              "BI",
              "BJ",
              "BN",
              "BO",
              "BR",
              "BS",
              "BW",
              "BY",
              "BZ",
              "CA",
              "CH",
              "CI",
              "CL",
              "CM",
              "CO",
              "CR",
              "CV",
              "CW",
              "CY",
              "CZ",
              "DE",
              "DJ",
              "DK",
              "DM",
              "DO",
              "DZ",
              "EC",
              "EE",
              "EG",
              "ES",
              "FI",
              "FJ",
              "FM",
              "FR",
              "GA",
              "GB",
              "GD",
              "GE",
              "GH",
              "GM",
              "GN",
              "GQ",
              "GR",
              "GT",
              "GW",
              "HK",
              "HN",
              "HR",
              "HT",
              "HU",
              "ID",
              "IE",
              "IL",
              "IN",
              "IS",
              "IT",
              "JM",
              "JO",
              "JP",
              "KE",
              "KG",
              "KH",
              "KM",
              "KN",
              "KR",
              "KW",
              "KZ",
              "LA",
              "LB",
              "LC",
              "LK",
              "LR",
              "LS",
              "LT",
              "LU",
              "LV",
              "MA",
              "MC",
              "MD",
              "ME",
              "MG",
              "MK",
              "ML",
              "MN",
              "MO",
              "MR",
              "MT",
              "MU",
              "MW",
              "MX",
              "MY",
              "MZ",
              "NA",
              "NE",
              "NG",
              "NI",
              "NL",
              "NO",
              "NP",
              "NZ",
              "OM",
              "PA",
              "PE",
              "PG",
              "PH",
              "PK",
              "PL",
              "PT",
              "PY",
              "QA",
              "RO",
              "RS",
              "RU",
              "RW",
              "SA",
              "SC",
              "SE",
              "SG",
              "SI",
              "SK",
              "SL",
              "SM",
              "SN",
              "ST",
              "SV",
              "SZ",
              "TD",
              "TG",
              "TH",
              "TL",
              "TN",
              "TR",
              "TT",
              "TW",
              "TZ",
              "UA",
              "UG",
              "US",
              "UY",
              "UZ",
              "VC",
              "VN",
              "XK",
              "ZA",
              "ZM",
              "ZW"
          ],
          "disc_number": 1,
          "duration_ms": 200813,
          "explicit": false,
          "external_urls": {
              "spotify": "https://open.spotify.com/track/6DrXZwTuhl5Ow4mcmSWjME"
          },
          "href": "https://api.spotify.com/v1/tracks/6DrXZwTuhl5Ow4mcmSWjME",
          "id": "6DrXZwTuhl5Ow4mcmSWjME",
          "is_local": false,
          "name": "Songbird - 2004 Remaster",
          "preview_url": "https://p.scdn.co/mp3-preview/ec134772e8876fa84bb531281e60c68c02a8f35f?cid=88e83947e4fb497e9c85307e40abab6c",
          "track_number": 6,
          "type": "track",
          "uri": "spotify:track:6DrXZwTuhl5Ow4mcmSWjME"
      },
      {
          "artists": [
              {
                  "external_urls": {
                      "spotify": "https://open.spotify.com/artist/08GQAI4eElDnROBrJRGE0X"
                  },
                  "href": "https://api.spotify.com/v1/artists/08GQAI4eElDnROBrJRGE0X",
                  "id": "08GQAI4eElDnROBrJRGE0X",
                  "name": "Fleetwood Mac",
                  "type": "artist",
                  "uri": "spotify:artist:08GQAI4eElDnROBrJRGE0X"
              }
          ],
          "available_markets": [
              "AD",
              "AE",
              "AG",
              "AL",
              "AM",
              "AO",
              "AR",
              "AT",
              "AU",
              "AZ",
              "BA",
              "BB",
              "BD",
              "BE",
              "BF",
              "BG",
              "BH",
              "BI",
              "BJ",
              "BN",
              "BO",
              "BR",
              "BS",
              "BW",
              "BY",
              "BZ",
              "CA",
              "CH",
              "CI",
              "CL",
              "CM",
              "CO",
              "CR",
              "CV",
              "CW",
              "CY",
              "CZ",
              "DE",
              "DJ",
              "DK",
              "DM",
              "DO",
              "DZ",
              "EC",
              "EE",
              "EG",
              "ES",
              "FI",
              "FJ",
              "FM",
              "FR",
              "GA",
              "GB",
              "GD",
              "GE",
              "GH",
              "GM",
              "GN",
              "GQ",
              "GR",
              "GT",
              "GW",
              "HK",
              "HN",
              "HR",
              "HT",
              "HU",
              "ID",
              "IE",
              "IL",
              "IN",
              "IS",
              "IT",
              "JM",
              "JO",
              "JP",
              "KE",
              "KG",
              "KH",
              "KM",
              "KN",
              "KR",
              "KW",
              "KZ",
              "LA",
              "LB",
              "LC",
              "LK",
              "LR",
              "LS",
              "LT",
              "LU",
              "LV",
              "MA",
              "MC",
              "MD",
              "ME",
              "MG",
              "MK",
              "ML",
              "MN",
              "MO",
              "MR",
              "MT",
              "MU",
              "MW",
              "MX",
              "MY",
              "MZ",
              "NA",
              "NE",
              "NG",
              "NI",
              "NL",
              "NO",
              "NP",
              "NZ",
              "OM",
              "PA",
              "PE",
              "PG",
              "PH",
              "PK",
              "PL",
              "PT",
              "PY",
              "QA",
              "RO",
              "RS",
              "RU",
              "RW",
              "SA",
              "SC",
              "SE",
              "SG",
              "SI",
              "SK",
              "SL",
              "SM",
              "SN",
              "ST",
              "SV",
              "SZ",
              "TD",
              "TG",
              "TH",
              "TL",
              "TN",
              "TR",
              "TT",
              "TW",
              "TZ",
              "UA",
              "UG",
              "US",
              "UY",
              "UZ",
              "VC",
              "VN",
              "XK",
              "ZA",
              "ZM",
              "ZW"
          ],
          "disc_number": 1,
          "duration_ms": 270213,
          "explicit": false,
          "external_urls": {
              "spotify": "https://open.spotify.com/track/5e9TFTbltYBg2xThimr0rU"
          },
          "href": "https://api.spotify.com/v1/tracks/5e9TFTbltYBg2xThimr0rU",
          "id": "5e9TFTbltYBg2xThimr0rU",
          "is_local": false,
          "name": "The Chain - 2004 Remaster",
          "preview_url": "https://p.scdn.co/mp3-preview/39267f043904cef22e6652c0ce761114321953fd?cid=88e83947e4fb497e9c85307e40abab6c",
          "track_number": 7,
          "type": "track",
          "uri": "spotify:track:5e9TFTbltYBg2xThimr0rU"
      },
      {
          "artists": [
              {
                  "external_urls": {
                      "spotify": "https://open.spotify.com/artist/08GQAI4eElDnROBrJRGE0X"
                  },
                  "href": "https://api.spotify.com/v1/artists/08GQAI4eElDnROBrJRGE0X",
                  "id": "08GQAI4eElDnROBrJRGE0X",
                  "name": "Fleetwood Mac",
                  "type": "artist",
                  "uri": "spotify:artist:08GQAI4eElDnROBrJRGE0X"
              }
          ],
          "available_markets": [
              "AD",
              "AE",
              "AG",
              "AL",
              "AM",
              "AO",
              "AR",
              "AT",
              "AU",
              "AZ",
              "BA",
              "BB",
              "BD",
              "BE",
              "BF",
              "BG",
              "BH",
              "BI",
              "BJ",
              "BN",
              "BO",
              "BR",
              "BS",
              "BW",
              "BY",
              "BZ",
              "CA",
              "CH",
              "CI",
              "CL",
              "CM",
              "CO",
              "CR",
              "CV",
              "CW",
              "CY",
              "CZ",
              "DE",
              "DJ",
              "DK",
              "DM",
              "DO",
              "DZ",
              "EC",
              "EE",
              "EG",
              "ES",
              "FI",
              "FJ",
              "FM",
              "FR",
              "GA",
              "GB",
              "GD",
              "GE",
              "GH",
              "GM",
              "GN",
              "GQ",
              "GR",
              "GT",
              "GW",
              "HK",
              "HN",
              "HR",
              "HT",
              "HU",
              "ID",
              "IE",
              "IL",
              "IN",
              "IS",
              "IT",
              "JM",
              "JO",
              "JP",
              "KE",
              "KG",
              "KH",
              "KM",
              "KN",
              "KR",
              "KW",
              "KZ",
              "LA",
              "LB",
              "LC",
              "LK",
              "LR",
              "LS",
              "LT",
              "LU",
              "LV",
              "MA",
              "MC",
              "MD",
              "ME",
              "MG",
              "MK",
              "ML",
              "MN",
              "MO",
              "MR",
              "MT",
              "MU",
              "MW",
              "MX",
              "MY",
              "MZ",
              "NA",
              "NE",
              "NG",
              "NI",
              "NL",
              "NO",
              "NP",
              "NZ",
              "OM",
              "PA",
              "PE",
              "PG",
              "PH",
              "PK",
              "PL",
              "PT",
              "PY",
              "QA",
              "RO",
              "RS",
              "RU",
              "RW",
              "SA",
              "SC",
              "SE",
              "SG",
              "SI",
              "SK",
              "SL",
              "SM",
              "SN",
              "ST",
              "SV",
              "SZ",
              "TD",
              "TG",
              "TH",
              "TL",
              "TN",
              "TR",
              "TT",
              "TW",
              "TZ",
              "UA",
              "UG",
              "US",
              "UY",
              "UZ",
              "VC",
              "VN",
              "XK",
              "ZA",
              "ZM",
              "ZW"
          ],
          "disc_number": 1,
          "duration_ms": 216626,
          "explicit": false,
          "external_urls": {
              "spotify": "https://open.spotify.com/track/55mQhobuwtY7lfLAXylg1k"
          },
          "href": "https://api.spotify.com/v1/tracks/55mQhobuwtY7lfLAXylg1k",
          "id": "55mQhobuwtY7lfLAXylg1k",
          "is_local": false,
          "name": "You Make Loving Fun - 2004 Remaster",
          "preview_url": "https://p.scdn.co/mp3-preview/c82f3cc408e0b63d853fa19cab0a60f5eb8742c5?cid=88e83947e4fb497e9c85307e40abab6c",
          "track_number": 8,
          "type": "track",
          "uri": "spotify:track:55mQhobuwtY7lfLAXylg1k"
      },
      {
          "artists": [
              {
                  "external_urls": {
                      "spotify": "https://open.spotify.com/artist/08GQAI4eElDnROBrJRGE0X"
                  },
                  "href": "https://api.spotify.com/v1/artists/08GQAI4eElDnROBrJRGE0X",
                  "id": "08GQAI4eElDnROBrJRGE0X",
                  "name": "Fleetwood Mac",
                  "type": "artist",
                  "uri": "spotify:artist:08GQAI4eElDnROBrJRGE0X"
              }
          ],
          "available_markets": [
              "AD",
              "AE",
              "AG",
              "AL",
              "AM",
              "AO",
              "AR",
              "AT",
              "AU",
              "AZ",
              "BA",
              "BB",
              "BD",
              "BE",
              "BF",
              "BG",
              "BH",
              "BI",
              "BJ",
              "BN",
              "BO",
              "BR",
              "BS",
              "BW",
              "BY",
              "BZ",
              "CA",
              "CH",
              "CI",
              "CL",
              "CM",
              "CO",
              "CR",
              "CV",
              "CW",
              "CY",
              "CZ",
              "DE",
              "DJ",
              "DK",
              "DM",
              "DO",
              "DZ",
              "EC",
              "EE",
              "EG",
              "ES",
              "FI",
              "FJ",
              "FM",
              "FR",
              "GA",
              "GB",
              "GD",
              "GE",
              "GH",
              "GM",
              "GN",
              "GQ",
              "GR",
              "GT",
              "GW",
              "HK",
              "HN",
              "HR",
              "HT",
              "HU",
              "ID",
              "IE",
              "IL",
              "IN",
              "IS",
              "IT",
              "JM",
              "JO",
              "JP",
              "KE",
              "KG",
              "KH",
              "KM",
              "KN",
              "KR",
              "KW",
              "KZ",
              "LA",
              "LB",
              "LC",
              "LK",
              "LR",
              "LS",
              "LT",
              "LU",
              "LV",
              "MA",
              "MC",
              "MD",
              "ME",
              "MG",
              "MK",
              "ML",
              "MN",
              "MO",
              "MR",
              "MT",
              "MU",
              "MW",
              "MX",
              "MY",
              "MZ",
              "NA",
              "NE",
              "NG",
              "NI",
              "NL",
              "NO",
              "NP",
              "NZ",
              "OM",
              "PA",
              "PE",
              "PG",
              "PH",
              "PK",
              "PL",
              "PT",
              "PY",
              "QA",
              "RO",
              "RS",
              "RU",
              "RW",
              "SA",
              "SC",
              "SE",
              "SG",
              "SI",
              "SK",
              "SL",
              "SM",
              "SN",
              "ST",
              "SV",
              "SZ",
              "TD",
              "TG",
              "TH",
              "TL",
              "TN",
              "TR",
              "TT",
              "TW",
              "TZ",
              "UA",
              "UG",
              "US",
              "UY",
              "UZ",
              "VC",
              "VN",
              "XK",
              "ZA",
              "ZM",
              "ZW"
          ],
          "disc_number": 1,
          "duration_ms": 196853,
          "explicit": false,
          "external_urls": {
              "spotify": "https://open.spotify.com/track/3B1lK5gNppO22gQLozrxeA"
          },
          "href": "https://api.spotify.com/v1/tracks/3B1lK5gNppO22gQLozrxeA",
          "id": "3B1lK5gNppO22gQLozrxeA",
          "is_local": false,
          "name": "I Don't Want to Know - 2004 Remaster",
          "preview_url": "https://p.scdn.co/mp3-preview/88f9280b86a894e83dfcc883b44f8778c590795d?cid=88e83947e4fb497e9c85307e40abab6c",
          "track_number": 9,
          "type": "track",
          "uri": "spotify:track:3B1lK5gNppO22gQLozrxeA"
      },
      {
          "artists": [
              {
                  "external_urls": {
                      "spotify": "https://open.spotify.com/artist/08GQAI4eElDnROBrJRGE0X"
                  },
                  "href": "https://api.spotify.com/v1/artists/08GQAI4eElDnROBrJRGE0X",
                  "id": "08GQAI4eElDnROBrJRGE0X",
                  "name": "Fleetwood Mac",
                  "type": "artist",
                  "uri": "spotify:artist:08GQAI4eElDnROBrJRGE0X"
              }
          ],
          "available_markets": [
              "AD",
              "AE",
              "AG",
              "AL",
              "AM",
              "AO",
              "AR",
              "AT",
              "AU",
              "AZ",
              "BA",
              "BB",
              "BD",
              "BE",
              "BF",
              "BG",
              "BH",
              "BI",
              "BJ",
              "BN",
              "BO",
              "BR",
              "BS",
              "BW",
              "BY",
              "BZ",
              "CA",
              "CH",
              "CI",
              "CL",
              "CM",
              "CO",
              "CR",
              "CV",
              "CW",
              "CY",
              "CZ",
              "DE",
              "DJ",
              "DK",
              "DM",
              "DO",
              "DZ",
              "EC",
              "EE",
              "EG",
              "ES",
              "FI",
              "FJ",
              "FM",
              "FR",
              "GA",
              "GB",
              "GD",
              "GE",
              "GH",
              "GM",
              "GN",
              "GQ",
              "GR",
              "GT",
              "GW",
              "HK",
              "HN",
              "HR",
              "HT",
              "HU",
              "ID",
              "IE",
              "IL",
              "IN",
              "IS",
              "IT",
              "JM",
              "JO",
              "JP",
              "KE",
              "KG",
              "KH",
              "KM",
              "KN",
              "KR",
              "KW",
              "KZ",
              "LA",
              "LB",
              "LC",
              "LK",
              "LR",
              "LS",
              "LT",
              "LU",
              "LV",
              "MA",
              "MC",
              "MD",
              "ME",
              "MG",
              "MK",
              "ML",
              "MN",
              "MO",
              "MR",
              "MT",
              "MU",
              "MW",
              "MX",
              "MY",
              "MZ",
              "NA",
              "NE",
              "NG",
              "NI",
              "NL",
              "NO",
              "NP",
              "NZ",
              "OM",
              "PA",
              "PE",
              "PG",
              "PH",
              "PK",
              "PL",
              "PT",
              "PY",
              "QA",
              "RO",
              "RS",
              "RU",
              "RW",
              "SA",
              "SC",
              "SE",
              "SG",
              "SI",
              "SK",
              "SL",
              "SM",
              "SN",
              "ST",
              "SV",
              "SZ",
              "TD",
              "TG",
              "TH",
              "TL",
              "TN",
              "TR",
              "TT",
              "TW",
              "TZ",
              "UA",
              "UG",
              "US",
              "UY",
              "UZ",
              "VC",
              "VN",
              "XK",
              "ZA",
              "ZM",
              "ZW"
          ],
          "disc_number": 1,
          "duration_ms": 236240,
          "explicit": false,
          "external_urls": {
              "spotify": "https://open.spotify.com/track/2wmr2A1ixEx9qViaOMkkkW"
          },
          "href": "https://api.spotify.com/v1/tracks/2wmr2A1ixEx9qViaOMkkkW",
          "id": "2wmr2A1ixEx9qViaOMkkkW",
          "is_local": false,
          "name": "Oh Daddy - 2004 Remaster",
          "preview_url": "https://p.scdn.co/mp3-preview/266436e2765352473b91028f0c25417528145299?cid=88e83947e4fb497e9c85307e40abab6c",
          "track_number": 10,
          "type": "track",
          "uri": "spotify:track:2wmr2A1ixEx9qViaOMkkkW"
      },
      {
          "artists": [
              {
                  "external_urls": {
                      "spotify": "https://open.spotify.com/artist/08GQAI4eElDnROBrJRGE0X"
                  },
                  "href": "https://api.spotify.com/v1/artists/08GQAI4eElDnROBrJRGE0X",
                  "id": "08GQAI4eElDnROBrJRGE0X",
                  "name": "Fleetwood Mac",
                  "type": "artist",
                  "uri": "spotify:artist:08GQAI4eElDnROBrJRGE0X"
              }
          ],
          "available_markets": [
              "AD",
              "AE",
              "AG",
              "AL",
              "AM",
              "AO",
              "AR",
              "AT",
              "AU",
              "AZ",
              "BA",
              "BB",
              "BD",
              "BE",
              "BF",
              "BG",
              "BH",
              "BI",
              "BJ",
              "BN",
              "BO",
              "BR",
              "BS",
              "BW",
              "BY",
              "BZ",
              "CA",
              "CH",
              "CI",
              "CL",
              "CM",
              "CO",
              "CR",
              "CV",
              "CW",
              "CY",
              "CZ",
              "DE",
              "DJ",
              "DK",
              "DM",
              "DO",
              "DZ",
              "EC",
              "EE",
              "EG",
              "ES",
              "FI",
              "FJ",
              "FM",
              "FR",
              "GA",
              "GB",
              "GD",
              "GE",
              "GH",
              "GM",
              "GN",
              "GQ",
              "GR",
              "GT",
              "GW",
              "HK",
              "HN",
              "HR",
              "HT",
              "HU",
              "ID",
              "IE",
              "IL",
              "IN",
              "IS",
              "IT",
              "JM",
              "JO",
              "JP",
              "KE",
              "KG",
              "KH",
              "KM",
              "KN",
              "KR",
              "KW",
              "KZ",
              "LA",
              "LB",
              "LC",
              "LK",
              "LR",
              "LS",
              "LT",
              "LU",
              "LV",
              "MA",
              "MC",
              "MD",
              "ME",
              "MG",
              "MK",
              "ML",
              "MN",
              "MO",
              "MR",
              "MT",
              "MU",
              "MW",
              "MX",
              "MY",
              "MZ",
              "NA",
              "NE",
              "NG",
              "NI",
              "NL",
              "NO",
              "NP",
              "NZ",
              "OM",
              "PA",
              "PE",
              "PG",
              "PH",
              "PK",
              "PL",
              "PT",
              "PY",
              "QA",
              "RO",
              "RS",
              "RU",
              "RW",
              "SA",
              "SC",
              "SE",
              "SG",
              "SI",
              "SK",
              "SL",
              "SM",
              "SN",
              "ST",
              "SV",
              "SZ",
              "TD",
              "TG",
              "TH",
              "TL",
              "TN",
              "TR",
              "TT",
              "TW",
              "TZ",
              "UA",
              "UG",
              "US",
              "UY",
              "UZ",
              "VC",
              "VN",
              "XK",
              "ZA",
              "ZM",
              "ZW"
          ],
          "disc_number": 1,
          "duration_ms": 295626,
          "explicit": false,
          "external_urls": {
              "spotify": "https://open.spotify.com/track/2ssyECwAX5JxtcAUTFw7wI"
          },
          "href": "https://api.spotify.com/v1/tracks/2ssyECwAX5JxtcAUTFw7wI",
          "id": "2ssyECwAX5JxtcAUTFw7wI",
          "is_local": false,
          "name": "Gold Dust Woman - 2004 Remaster",
          "preview_url": "https://p.scdn.co/mp3-preview/92ae935e9c16b3109ec83a49c77026b4fccc7ae9?cid=88e83947e4fb497e9c85307e40abab6c",
          "track_number": 11,
          "type": "track",
          "uri": "spotify:track:2ssyECwAX5JxtcAUTFw7wI"
      },
      {
          "artists": [
              {
                  "external_urls": {
                      "spotify": "https://open.spotify.com/artist/08GQAI4eElDnROBrJRGE0X"
                  },
                  "href": "https://api.spotify.com/v1/artists/08GQAI4eElDnROBrJRGE0X",
                  "id": "08GQAI4eElDnROBrJRGE0X",
                  "name": "Fleetwood Mac",
                  "type": "artist",
                  "uri": "spotify:artist:08GQAI4eElDnROBrJRGE0X"
              }
          ],
          "available_markets": [
              "AD",
              "AE",
              "AG",
              "AL",
              "AM",
              "AO",
              "AR",
              "AT",
              "AU",
              "AZ",
              "BA",
              "BB",
              "BD",
              "BE",
              "BF",
              "BG",
              "BH",
              "BI",
              "BJ",
              "BN",
              "BO",
              "BR",
              "BS",
              "BW",
              "BY",
              "BZ",
              "CA",
              "CH",
              "CI",
              "CL",
              "CM",
              "CO",
              "CR",
              "CV",
              "CW",
              "CY",
              "CZ",
              "DE",
              "DJ",
              "DK",
              "DM",
              "DO",
              "DZ",
              "EC",
              "EE",
              "EG",
              "ES",
              "FI",
              "FJ",
              "FM",
              "FR",
              "GA",
              "GB",
              "GD",
              "GE",
              "GH",
              "GM",
              "GN",
              "GQ",
              "GR",
              "GT",
              "GW",
              "HK",
              "HN",
              "HR",
              "HT",
              "HU",
              "ID",
              "IE",
              "IL",
              "IN",
              "IS",
              "IT",
              "JM",
              "JO",
              "JP",
              "KE",
              "KG",
              "KH",
              "KM",
              "KN",
              "KR",
              "KW",
              "KZ",
              "LA",
              "LB",
              "LC",
              "LK",
              "LR",
              "LS",
              "LT",
              "LU",
              "LV",
              "MA",
              "MC",
              "MD",
              "ME",
              "MG",
              "MK",
              "ML",
              "MN",
              "MO",
              "MR",
              "MT",
              "MU",
              "MW",
              "MX",
              "MY",
              "MZ",
              "NA",
              "NE",
              "NG",
              "NI",
              "NL",
              "NO",
              "NP",
              "NZ",
              "OM",
              "PA",
              "PE",
              "PG",
              "PH",
              "PK",
              "PL",
              "PT",
              "PY",
              "QA",
              "RO",
              "RS",
              "RU",
              "RW",
              "SA",
              "SC",
              "SE",
              "SG",
              "SI",
              "SK",
              "SL",
              "SM",
              "SN",
              "ST",
              "SV",
              "SZ",
              "TD",
              "TG",
              "TH",
              "TL",
              "TN",
              "TR",
              "TT",
              "TW",
              "TZ",
              "UA",
              "UG",
              "US",
              "UY",
              "UZ",
              "VC",
              "VN",
              "XK",
              "ZA",
              "ZM",
              "ZW"
          ],
          "disc_number": 1,
          "duration_ms": 288786,
          "explicit": false,
          "external_urls": {
              "spotify": "https://open.spotify.com/track/4nZi6XNe36Ut4Nij3IQ1yC"
          },
          "href": "https://api.spotify.com/v1/tracks/4nZi6XNe36Ut4Nij3IQ1yC",
          "id": "4nZi6XNe36Ut4Nij3IQ1yC",
          "is_local": false,
          "name": "Silver Springs - 2004 Remaster",
          "preview_url": "https://p.scdn.co/mp3-preview/ea722a244f4c354c0213bb09a65fa2934f42f8ba?cid=88e83947e4fb497e9c85307e40abab6c",
          "track_number": 12,
          "type": "track",
          "uri": "spotify:track:4nZi6XNe36Ut4Nij3IQ1yC"
      },
      {
          "artists": [
              {
                  "external_urls": {
                      "spotify": "https://open.spotify.com/artist/08GQAI4eElDnROBrJRGE0X"
                  },
                  "href": "https://api.spotify.com/v1/artists/08GQAI4eElDnROBrJRGE0X",
                  "id": "08GQAI4eElDnROBrJRGE0X",
                  "name": "Fleetwood Mac",
                  "type": "artist",
                  "uri": "spotify:artist:08GQAI4eElDnROBrJRGE0X"
              }
          ],
          "available_markets": [
              "AD",
              "AE",
              "AG",
              "AL",
              "AM",
              "AO",
              "AR",
              "AT",
              "AU",
              "AZ",
              "BA",
              "BB",
              "BD",
              "BE",
              "BF",
              "BG",
              "BH",
              "BI",
              "BJ",
              "BN",
              "BO",
              "BR",
              "BS",
              "BW",
              "BY",
              "BZ",
              "CA",
              "CH",
              "CI",
              "CL",
              "CM",
              "CO",
              "CR",
              "CV",
              "CW",
              "CY",
              "CZ",
              "DE",
              "DJ",
              "DK",
              "DM",
              "DO",
              "DZ",
              "EC",
              "EE",
              "EG",
              "ES",
              "FI",
              "FJ",
              "FM",
              "FR",
              "GA",
              "GB",
              "GD",
              "GE",
              "GH",
              "GM",
              "GN",
              "GQ",
              "GR",
              "GT",
              "GW",
              "HK",
              "HN",
              "HR",
              "HT",
              "HU",
              "ID",
              "IE",
              "IL",
              "IN",
              "IS",
              "IT",
              "JM",
              "JO",
              "JP",
              "KE",
              "KG",
              "KH",
              "KM",
              "KN",
              "KR",
              "KW",
              "KZ",
              "LA",
              "LB",
              "LC",
              "LK",
              "LR",
              "LS",
              "LT",
              "LU",
              "LV",
              "MA",
              "MC",
              "MD",
              "ME",
              "MG",
              "MK",
              "ML",
              "MN",
              "MO",
              "MR",
              "MT",
              "MU",
              "MW",
              "MX",
              "MY",
              "MZ",
              "NA",
              "NE",
              "NG",
              "NI",
              "NL",
              "NO",
              "NP",
              "NZ",
              "OM",
              "PA",
              "PE",
              "PG",
              "PH",
              "PK",
              "PL",
              "PT",
              "PY",
              "QA",
              "RO",
              "RS",
              "RU",
              "RW",
              "SA",
              "SC",
              "SE",
              "SG",
              "SI",
              "SK",
              "SL",
              "SM",
              "SN",
              "ST",
              "SV",
              "SZ",
              "TD",
              "TG",
              "TH",
              "TL",
              "TN",
              "TR",
              "TT",
              "TW",
              "TZ",
              "UA",
              "UG",
              "US",
              "UY",
              "UZ",
              "VC",
              "VN",
              "XK",
              "ZA",
              "ZM",
              "ZW"
          ],
          "disc_number": 2,
          "duration_ms": 48373,
          "explicit": false,
          "external_urls": {
              "spotify": "https://open.spotify.com/track/7iPabscOgrBuDkjZAvOVRD"
          },
          "href": "https://api.spotify.com/v1/tracks/7iPabscOgrBuDkjZAvOVRD",
          "id": "7iPabscOgrBuDkjZAvOVRD",
          "is_local": false,
          "name": "Intro - Live 1977",
          "preview_url": "https://p.scdn.co/mp3-preview/a18457cc3f8b4f6d4f5fb715284b17659f7e8e22?cid=88e83947e4fb497e9c85307e40abab6c",
          "track_number": 1,
          "type": "track",
          "uri": "spotify:track:7iPabscOgrBuDkjZAvOVRD"
      },
      {
          "artists": [
              {
                  "external_urls": {
                      "spotify": "https://open.spotify.com/artist/08GQAI4eElDnROBrJRGE0X"
                  },
                  "href": "https://api.spotify.com/v1/artists/08GQAI4eElDnROBrJRGE0X",
                  "id": "08GQAI4eElDnROBrJRGE0X",
                  "name": "Fleetwood Mac",
                  "type": "artist",
                  "uri": "spotify:artist:08GQAI4eElDnROBrJRGE0X"
              }
          ],
          "available_markets": [
              "AD",
              "AE",
              "AG",
              "AL",
              "AM",
              "AO",
              "AR",
              "AT",
              "AU",
              "AZ",
              "BA",
              "BB",
              "BD",
              "BE",
              "BF",
              "BG",
              "BH",
              "BI",
              "BJ",
              "BN",
              "BO",
              "BR",
              "BS",
              "BW",
              "BY",
              "BZ",
              "CA",
              "CH",
              "CI",
              "CL",
              "CM",
              "CO",
              "CR",
              "CV",
              "CW",
              "CY",
              "CZ",
              "DE",
              "DJ",
              "DK",
              "DM",
              "DO",
              "DZ",
              "EC",
              "EE",
              "EG",
              "ES",
              "FI",
              "FJ",
              "FM",
              "FR",
              "GA",
              "GB",
              "GD",
              "GE",
              "GH",
              "GM",
              "GN",
              "GQ",
              "GR",
              "GT",
              "GW",
              "HK",
              "HN",
              "HR",
              "HT",
              "HU",
              "ID",
              "IE",
              "IL",
              "IN",
              "IS",
              "IT",
              "JM",
              "JO",
              "JP",
              "KE",
              "KG",
              "KH",
              "KM",
              "KN",
              "KR",
              "KW",
              "KZ",
              "LA",
              "LB",
              "LC",
              "LK",
              "LR",
              "LS",
              "LT",
              "LU",
              "LV",
              "MA",
              "MC",
              "MD",
              "ME",
              "MG",
              "MK",
              "ML",
              "MN",
              "MO",
              "MR",
              "MT",
              "MU",
              "MW",
              "MX",
              "MY",
              "MZ",
              "NA",
              "NE",
              "NG",
              "NI",
              "NL",
              "NO",
              "NP",
              "NZ",
              "OM",
              "PA",
              "PE",
              "PG",
              "PH",
              "PK",
              "PL",
              "PT",
              "PY",
              "QA",
              "RO",
              "RS",
              "RU",
              "RW",
              "SA",
              "SC",
              "SE",
              "SG",
              "SI",
              "SK",
              "SL",
              "SM",
              "SN",
              "ST",
              "SV",
              "SZ",
              "TD",
              "TG",
              "TH",
              "TL",
              "TN",
              "TR",
              "TT",
              "TW",
              "TZ",
              "UA",
              "UG",
              "US",
              "UY",
              "UZ",
              "VC",
              "VN",
              "XK",
              "ZA",
              "ZM",
              "ZW"
          ],
          "disc_number": 2,
          "duration_ms": 158893,
          "explicit": false,
          "external_urls": {
              "spotify": "https://open.spotify.com/track/2LWGrxEKOgcOjtkiuX0OPL"
          },
          "href": "https://api.spotify.com/v1/tracks/2LWGrxEKOgcOjtkiuX0OPL",
          "id": "2LWGrxEKOgcOjtkiuX0OPL",
          "is_local": false,
          "name": "Monday Morning - Live at The Fabulous Forum, Inglewood, CA 08/29/77",
          "preview_url": "https://p.scdn.co/mp3-preview/b9ecd4b80c2da15ecbe289a71d15f3fe829f7d37?cid=88e83947e4fb497e9c85307e40abab6c",
          "track_number": 2,
          "type": "track",
          "uri": "spotify:track:2LWGrxEKOgcOjtkiuX0OPL"
      },
      {
          "artists": [
              {
                  "external_urls": {
                      "spotify": "https://open.spotify.com/artist/08GQAI4eElDnROBrJRGE0X"
                  },
                  "href": "https://api.spotify.com/v1/artists/08GQAI4eElDnROBrJRGE0X",
                  "id": "08GQAI4eElDnROBrJRGE0X",
                  "name": "Fleetwood Mac",
                  "type": "artist",
                  "uri": "spotify:artist:08GQAI4eElDnROBrJRGE0X"
              }
          ],
          "available_markets": [
              "AD",
              "AE",
              "AG",
              "AL",
              "AM",
              "AO",
              "AR",
              "AT",
              "AU",
              "AZ",
              "BA",
              "BB",
              "BD",
              "BE",
              "BF",
              "BG",
              "BH",
              "BI",
              "BJ",
              "BN",
              "BO",
              "BR",
              "BS",
              "BW",
              "BY",
              "BZ",
              "CA",
              "CH",
              "CI",
              "CL",
              "CM",
              "CO",
              "CR",
              "CV",
              "CW",
              "CY",
              "CZ",
              "DE",
              "DJ",
              "DK",
              "DM",
              "DO",
              "DZ",
              "EC",
              "EE",
              "EG",
              "ES",
              "FI",
              "FJ",
              "FM",
              "FR",
              "GA",
              "GB",
              "GD",
              "GE",
              "GH",
              "GM",
              "GN",
              "GQ",
              "GR",
              "GT",
              "GW",
              "HK",
              "HN",
              "HR",
              "HT",
              "HU",
              "ID",
              "IE",
              "IL",
              "IN",
              "IS",
              "IT",
              "JM",
              "JO",
              "JP",
              "KE",
              "KG",
              "KH",
              "KM",
              "KN",
              "KR",
              "KW",
              "KZ",
              "LA",
              "LB",
              "LC",
              "LK",
              "LR",
              "LS",
              "LT",
              "LU",
              "LV",
              "MA",
              "MC",
              "MD",
              "ME",
              "MG",
              "MK",
              "ML",
              "MN",
              "MO",
              "MR",
              "MT",
              "MU",
              "MW",
              "MX",
              "MY",
              "MZ",
              "NA",
              "NE",
              "NG",
              "NI",
              "NL",
              "NO",
              "NP",
              "NZ",
              "OM",
              "PA",
              "PE",
              "PG",
              "PH",
              "PK",
              "PL",
              "PT",
              "PY",
              "QA",
              "RO",
              "RS",
              "RU",
              "RW",
              "SA",
              "SC",
              "SE",
              "SG",
              "SI",
              "SK",
              "SL",
              "SM",
              "SN",
              "ST",
              "SV",
              "SZ",
              "TD",
              "TG",
              "TH",
              "TL",
              "TN",
              "TR",
              "TT",
              "TW",
              "TZ",
              "UA",
              "UG",
              "US",
              "UY",
              "UZ",
              "VC",
              "VN",
              "XK",
              "ZA",
              "ZM",
              "ZW"
          ],
          "disc_number": 2,
          "duration_ms": 247213,
          "explicit": false,
          "external_urls": {
              "spotify": "https://open.spotify.com/track/5HY7oAMG0FSMewubwIf3iS"
          },
          "href": "https://api.spotify.com/v1/tracks/5HY7oAMG0FSMewubwIf3iS",
          "id": "5HY7oAMG0FSMewubwIf3iS",
          "is_local": false,
          "name": "Dreams - Live 1977",
          "preview_url": "https://p.scdn.co/mp3-preview/7f899d81406803cee3a4f376f74ea3614e20aa33?cid=88e83947e4fb497e9c85307e40abab6c",
          "track_number": 3,
          "type": "track",
          "uri": "spotify:track:5HY7oAMG0FSMewubwIf3iS"
      },
      {
          "artists": [
              {
                  "external_urls": {
                      "spotify": "https://open.spotify.com/artist/08GQAI4eElDnROBrJRGE0X"
                  },
                  "href": "https://api.spotify.com/v1/artists/08GQAI4eElDnROBrJRGE0X",
                  "id": "08GQAI4eElDnROBrJRGE0X",
                  "name": "Fleetwood Mac",
                  "type": "artist",
                  "uri": "spotify:artist:08GQAI4eElDnROBrJRGE0X"
              }
          ],
          "available_markets": [
              "AD",
              "AE",
              "AG",
              "AL",
              "AM",
              "AO",
              "AR",
              "AT",
              "AU",
              "AZ",
              "BA",
              "BB",
              "BD",
              "BE",
              "BF",
              "BG",
              "BH",
              "BI",
              "BJ",
              "BN",
              "BO",
              "BR",
              "BS",
              "BW",
              "BY",
              "BZ",
              "CA",
              "CH",
              "CI",
              "CL",
              "CM",
              "CO",
              "CR",
              "CV",
              "CW",
              "CY",
              "CZ",
              "DE",
              "DJ",
              "DK",
              "DM",
              "DO",
              "DZ",
              "EC",
              "EE",
              "EG",
              "ES",
              "FI",
              "FJ",
              "FM",
              "FR",
              "GA",
              "GB",
              "GD",
              "GE",
              "GH",
              "GM",
              "GN",
              "GQ",
              "GR",
              "GT",
              "GW",
              "HK",
              "HN",
              "HR",
              "HT",
              "HU",
              "ID",
              "IE",
              "IL",
              "IN",
              "IS",
              "IT",
              "JM",
              "JO",
              "JP",
              "KE",
              "KG",
              "KH",
              "KM",
              "KN",
              "KR",
              "KW",
              "KZ",
              "LA",
              "LB",
              "LC",
              "LK",
              "LR",
              "LS",
              "LT",
              "LU",
              "LV",
              "MA",
              "MC",
              "MD",
              "ME",
              "MG",
              "MK",
              "ML",
              "MN",
              "MO",
              "MR",
              "MT",
              "MU",
              "MW",
              "MX",
              "MY",
              "MZ",
              "NA",
              "NE",
              "NG",
              "NI",
              "NL",
              "NO",
              "NP",
              "NZ",
              "OM",
              "PA",
              "PE",
              "PG",
              "PH",
              "PK",
              "PL",
              "PT",
              "PY",
              "QA",
              "RO",
              "RS",
              "RU",
              "RW",
              "SA",
              "SC",
              "SE",
              "SG",
              "SI",
              "SK",
              "SL",
              "SM",
              "SN",
              "ST",
              "SV",
              "SZ",
              "TD",
              "TG",
              "TH",
              "TL",
              "TN",
              "TR",
              "TT",
              "TW",
              "TZ",
              "UA",
              "UG",
              "US",
              "UY",
              "UZ",
              "VC",
              "VN",
              "XK",
              "ZA",
              "ZM",
              "ZW"
          ],
          "disc_number": 2,
          "duration_ms": 231653,
          "explicit": false,
          "external_urls": {
              "spotify": "https://open.spotify.com/track/7uY8cyuuGiAMaYBZ9mOYxy"
          },
          "href": "https://api.spotify.com/v1/tracks/7uY8cyuuGiAMaYBZ9mOYxy",
          "id": "7uY8cyuuGiAMaYBZ9mOYxy",
          "is_local": false,
          "name": "Don't Stop - Live 1977",
          "preview_url": "https://p.scdn.co/mp3-preview/ad7d2bbec68956b2b03606235dce22fb2a4254de?cid=88e83947e4fb497e9c85307e40abab6c",
          "track_number": 4,
          "type": "track",
          "uri": "spotify:track:7uY8cyuuGiAMaYBZ9mOYxy"
      },
      {
          "artists": [
              {
                  "external_urls": {
                      "spotify": "https://open.spotify.com/artist/08GQAI4eElDnROBrJRGE0X"
                  },
                  "href": "https://api.spotify.com/v1/artists/08GQAI4eElDnROBrJRGE0X",
                  "id": "08GQAI4eElDnROBrJRGE0X",
                  "name": "Fleetwood Mac",
                  "type": "artist",
                  "uri": "spotify:artist:08GQAI4eElDnROBrJRGE0X"
              }
          ],
          "available_markets": [
              "AD",
              "AE",
              "AG",
              "AL",
              "AM",
              "AO",
              "AR",
              "AT",
              "AU",
              "AZ",
              "BA",
              "BB",
              "BD",
              "BE",
              "BF",
              "BG",
              "BH",
              "BI",
              "BJ",
              "BN",
              "BO",
              "BR",
              "BS",
              "BW",
              "BY",
              "BZ",
              "CA",
              "CH",
              "CI",
              "CL",
              "CM",
              "CO",
              "CR",
              "CV",
              "CW",
              "CY",
              "CZ",
              "DE",
              "DJ",
              "DK",
              "DM",
              "DO",
              "DZ",
              "EC",
              "EE",
              "EG",
              "ES",
              "FI",
              "FJ",
              "FM",
              "FR",
              "GA",
              "GB",
              "GD",
              "GE",
              "GH",
              "GM",
              "GN",
              "GQ",
              "GR",
              "GT",
              "GW",
              "HK",
              "HN",
              "HR",
              "HT",
              "HU",
              "ID",
              "IE",
              "IL",
              "IN",
              "IS",
              "IT",
              "JM",
              "JO",
              "JP",
              "KE",
              "KG",
              "KH",
              "KM",
              "KN",
              "KR",
              "KW",
              "KZ",
              "LA",
              "LB",
              "LC",
              "LK",
              "LR",
              "LS",
              "LT",
              "LU",
              "LV",
              "MA",
              "MC",
              "MD",
              "ME",
              "MG",
              "MK",
              "ML",
              "MN",
              "MO",
              "MR",
              "MT",
              "MU",
              "MW",
              "MX",
              "MY",
              "MZ",
              "NA",
              "NE",
              "NG",
              "NI",
              "NL",
              "NO",
              "NP",
              "NZ",
              "OM",
              "PA",
              "PE",
              "PG",
              "PH",
              "PK",
              "PL",
              "PT",
              "PY",
              "QA",
              "RO",
              "RS",
              "RU",
              "RW",
              "SA",
              "SC",
              "SE",
              "SG",
              "SI",
              "SK",
              "SL",
              "SM",
              "SN",
              "ST",
              "SV",
              "SZ",
              "TD",
              "TG",
              "TH",
              "TL",
              "TN",
              "TR",
              "TT",
              "TW",
              "TZ",
              "UA",
              "UG",
              "US",
              "UY",
              "UZ",
              "VC",
              "VN",
              "XK",
              "ZA",
              "ZM",
              "ZW"
          ],
          "disc_number": 2,
          "duration_ms": 340533,
          "explicit": false,
          "external_urls": {
              "spotify": "https://open.spotify.com/track/5m5XW67LO8x72K0GusruVA"
          },
          "href": "https://api.spotify.com/v1/tracks/5m5XW67LO8x72K0GusruVA",
          "id": "5m5XW67LO8x72K0GusruVA",
          "is_local": false,
          "name": "The Chain - Live 1977",
          "preview_url": "https://p.scdn.co/mp3-preview/50cd138510befd44d7a0fdccd7764a8260070da6?cid=88e83947e4fb497e9c85307e40abab6c",
          "track_number": 5,
          "type": "track",
          "uri": "spotify:track:5m5XW67LO8x72K0GusruVA"
      },
      {
          "artists": [
              {
                  "external_urls": {
                      "spotify": "https://open.spotify.com/artist/08GQAI4eElDnROBrJRGE0X"
                  },
                  "href": "https://api.spotify.com/v1/artists/08GQAI4eElDnROBrJRGE0X",
                  "id": "08GQAI4eElDnROBrJRGE0X",
                  "name": "Fleetwood Mac",
                  "type": "artist",
                  "uri": "spotify:artist:08GQAI4eElDnROBrJRGE0X"
              }
          ],
          "available_markets": [
              "AD",
              "AE",
              "AG",
              "AL",
              "AM",
              "AO",
              "AR",
              "AT",
              "AU",
              "AZ",
              "BA",
              "BB",
              "BD",
              "BE",
              "BF",
              "BG",
              "BH",
              "BI",
              "BJ",
              "BN",
              "BO",
              "BR",
              "BS",
              "BW",
              "BY",
              "BZ",
              "CA",
              "CH",
              "CI",
              "CL",
              "CM",
              "CO",
              "CR",
              "CV",
              "CW",
              "CY",
              "CZ",
              "DE",
              "DJ",
              "DK",
              "DM",
              "DO",
              "DZ",
              "EC",
              "EE",
              "EG",
              "ES",
              "FI",
              "FJ",
              "FM",
              "FR",
              "GA",
              "GB",
              "GD",
              "GE",
              "GH",
              "GM",
              "GN",
              "GQ",
              "GR",
              "GT",
              "GW",
              "HK",
              "HN",
              "HR",
              "HT",
              "HU",
              "ID",
              "IE",
              "IL",
              "IN",
              "IS",
              "IT",
              "JM",
              "JO",
              "JP",
              "KE",
              "KG",
              "KH",
              "KM",
              "KN",
              "KR",
              "KW",
              "KZ",
              "LA",
              "LB",
              "LC",
              "LK",
              "LR",
              "LS",
              "LT",
              "LU",
              "LV",
              "MA",
              "MC",
              "MD",
              "ME",
              "MG",
              "MK",
              "ML",
              "MN",
              "MO",
              "MR",
              "MT",
              "MU",
              "MW",
              "MX",
              "MY",
              "MZ",
              "NA",
              "NE",
              "NG",
              "NI",
              "NL",
              "NO",
              "NP",
              "NZ",
              "OM",
              "PA",
              "PE",
              "PG",
              "PH",
              "PK",
              "PL",
              "PT",
              "PY",
              "QA",
              "RO",
              "RS",
              "RU",
              "RW",
              "SA",
              "SC",
              "SE",
              "SG",
              "SI",
              "SK",
              "SL",
              "SM",
              "SN",
              "ST",
              "SV",
              "SZ",
              "TD",
              "TG",
              "TH",
              "TL",
              "TN",
              "TR",
              "TT",
              "TW",
              "TZ",
              "UA",
              "UG",
              "US",
              "UY",
              "UZ",
              "VC",
              "VN",
              "XK",
              "ZA",
              "ZM",
              "ZW"
          ],
          "disc_number": 2,
          "duration_ms": 287866,
          "explicit": false,
          "external_urls": {
              "spotify": "https://open.spotify.com/track/4Cv8KLIBrN25GRIJ3aeWq2"
          },
          "href": "https://api.spotify.com/v1/tracks/4Cv8KLIBrN25GRIJ3aeWq2",
          "id": "4Cv8KLIBrN25GRIJ3aeWq2",
          "is_local": false,
          "name": "Oh Daddy - Live 1977",
          "preview_url": "https://p.scdn.co/mp3-preview/29a847b508b7c4e8b6160a985c828584f0e7c3bb?cid=88e83947e4fb497e9c85307e40abab6c",
          "track_number": 6,
          "type": "track",
          "uri": "spotify:track:4Cv8KLIBrN25GRIJ3aeWq2"
      },
      {
          "artists": [
              {
                  "external_urls": {
                      "spotify": "https://open.spotify.com/artist/08GQAI4eElDnROBrJRGE0X"
                  },
                  "href": "https://api.spotify.com/v1/artists/08GQAI4eElDnROBrJRGE0X",
                  "id": "08GQAI4eElDnROBrJRGE0X",
                  "name": "Fleetwood Mac",
                  "type": "artist",
                  "uri": "spotify:artist:08GQAI4eElDnROBrJRGE0X"
              }
          ],
          "available_markets": [
              "AD",
              "AE",
              "AG",
              "AL",
              "AM",
              "AO",
              "AR",
              "AT",
              "AU",
              "AZ",
              "BA",
              "BB",
              "BD",
              "BE",
              "BF",
              "BG",
              "BH",
              "BI",
              "BJ",
              "BN",
              "BO",
              "BR",
              "BS",
              "BW",
              "BY",
              "BZ",
              "CA",
              "CH",
              "CI",
              "CL",
              "CM",
              "CO",
              "CR",
              "CV",
              "CW",
              "CY",
              "CZ",
              "DE",
              "DJ",
              "DK",
              "DM",
              "DO",
              "DZ",
              "EC",
              "EE",
              "EG",
              "ES",
              "FI",
              "FJ",
              "FM",
              "FR",
              "GA",
              "GB",
              "GD",
              "GE",
              "GH",
              "GM",
              "GN",
              "GQ",
              "GR",
              "GT",
              "GW",
              "HK",
              "HN",
              "HR",
              "HT",
              "HU",
              "ID",
              "IE",
              "IL",
              "IN",
              "IS",
              "IT",
              "JM",
              "JO",
              "JP",
              "KE",
              "KG",
              "KH",
              "KM",
              "KN",
              "KR",
              "KW",
              "KZ",
              "LA",
              "LB",
              "LC",
              "LK",
              "LR",
              "LS",
              "LT",
              "LU",
              "LV",
              "MA",
              "MC",
              "MD",
              "ME",
              "MG",
              "MK",
              "ML",
              "MN",
              "MO",
              "MR",
              "MT",
              "MU",
              "MW",
              "MX",
              "MY",
              "MZ",
              "NA",
              "NE",
              "NG",
              "NI",
              "NL",
              "NO",
              "NP",
              "NZ",
              "OM",
              "PA",
              "PE",
              "PG",
              "PH",
              "PK",
              "PL",
              "PT",
              "PY",
              "QA",
              "RO",
              "RS",
              "RU",
              "RW",
              "SA",
              "SC",
              "SE",
              "SG",
              "SI",
              "SK",
              "SL",
              "SM",
              "SN",
              "ST",
              "SV",
              "SZ",
              "TD",
              "TG",
              "TH",
              "TL",
              "TN",
              "TR",
              "TT",
              "TW",
              "TZ",
              "UA",
              "UG",
              "US",
              "UY",
              "UZ",
              "VC",
              "VN",
              "XK",
              "ZA",
              "ZM",
              "ZW"
          ],
          "disc_number": 2,
          "duration_ms": 475306,
          "explicit": false,
          "external_urls": {
              "spotify": "https://open.spotify.com/track/1nWyUagJmVzvBGTMDeY73L"
          },
          "href": "https://api.spotify.com/v1/tracks/1nWyUagJmVzvBGTMDeY73L",
          "id": "1nWyUagJmVzvBGTMDeY73L",
          "is_local": false,
          "name": "Rhiannon - Live 1977",
          "preview_url": "https://p.scdn.co/mp3-preview/31eaba77e38a3dc7a9e099a9706f8aa1b4ffb263?cid=88e83947e4fb497e9c85307e40abab6c",
          "track_number": 7,
          "type": "track",
          "uri": "spotify:track:1nWyUagJmVzvBGTMDeY73L"
      },
      {
          "artists": [
              {
                  "external_urls": {
                      "spotify": "https://open.spotify.com/artist/08GQAI4eElDnROBrJRGE0X"
                  },
                  "href": "https://api.spotify.com/v1/artists/08GQAI4eElDnROBrJRGE0X",
                  "id": "08GQAI4eElDnROBrJRGE0X",
                  "name": "Fleetwood Mac",
                  "type": "artist",
                  "uri": "spotify:artist:08GQAI4eElDnROBrJRGE0X"
              }
          ],
          "available_markets": [
              "AD",
              "AE",
              "AG",
              "AL",
              "AM",
              "AO",
              "AR",
              "AT",
              "AU",
              "AZ",
              "BA",
              "BB",
              "BD",
              "BE",
              "BF",
              "BG",
              "BH",
              "BI",
              "BJ",
              "BN",
              "BO",
              "BR",
              "BS",
              "BW",
              "BY",
              "BZ",
              "CA",
              "CH",
              "CI",
              "CL",
              "CM",
              "CO",
              "CR",
              "CV",
              "CW",
              "CY",
              "CZ",
              "DE",
              "DJ",
              "DK",
              "DM",
              "DO",
              "DZ",
              "EC",
              "EE",
              "EG",
              "ES",
              "FI",
              "FJ",
              "FM",
              "FR",
              "GA",
              "GB",
              "GD",
              "GE",
              "GH",
              "GM",
              "GN",
              "GQ",
              "GR",
              "GT",
              "GW",
              "HK",
              "HN",
              "HR",
              "HT",
              "HU",
              "ID",
              "IE",
              "IL",
              "IN",
              "IS",
              "IT",
              "JM",
              "JO",
              "JP",
              "KE",
              "KG",
              "KH",
              "KM",
              "KN",
              "KR",
              "KW",
              "KZ",
              "LA",
              "LB",
              "LC",
              "LK",
              "LR",
              "LS",
              "LT",
              "LU",
              "LV",
              "MA",
              "MC",
              "MD",
              "ME",
              "MG",
              "MK",
              "ML",
              "MN",
              "MO",
              "MR",
              "MT",
              "MU",
              "MW",
              "MX",
              "MY",
              "MZ",
              "NA",
              "NE",
              "NG",
              "NI",
              "NL",
              "NO",
              "NP",
              "NZ",
              "OM",
              "PA",
              "PE",
              "PG",
              "PH",
              "PK",
              "PL",
              "PT",
              "PY",
              "QA",
              "RO",
              "RS",
              "RU",
              "RW",
              "SA",
              "SC",
              "SE",
              "SG",
              "SI",
              "SK",
              "SL",
              "SM",
              "SN",
              "ST",
              "SV",
              "SZ",
              "TD",
              "TG",
              "TH",
              "TL",
              "TN",
              "TR",
              "TT",
              "TW",
              "TZ",
              "UA",
              "UG",
              "US",
              "UY",
              "UZ",
              "VC",
              "VN",
              "XK",
              "ZA",
              "ZM",
              "ZW"
          ],
          "disc_number": 2,
          "duration_ms": 139960,
          "explicit": false,
          "external_urls": {
              "spotify": "https://open.spotify.com/track/3q19zFJpKJIaUGyiCyIRTM"
          },
          "href": "https://api.spotify.com/v1/tracks/3q19zFJpKJIaUGyiCyIRTM",
          "id": "3q19zFJpKJIaUGyiCyIRTM",
          "is_local": false,
          "name": "Never Going Back Again - Live 1977",
          "preview_url": "https://p.scdn.co/mp3-preview/f39f3e648c52bff0561d0803ab90b45774d6be3f?cid=88e83947e4fb497e9c85307e40abab6c",
          "track_number": 8,
          "type": "track",
          "uri": "spotify:track:3q19zFJpKJIaUGyiCyIRTM"
      }
  ],
  "limit": 20,
  "next": "https://api.spotify.com/v1/albums/0BwWUstDMUbgq2NYONRqlu/tracks?offset=20&limit=20",
  "offset": 0,
  "previous": null,
  "total": 58
};